-- agent-service 测试 schema：只保留它真正读的一列（§19.4 入口查账号状态）。
CREATE TABLE sys_user (
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'active'
);

INSERT INTO sys_user (id, username, password_hash, display_name, status) VALUES
    (1, 'alice', 'x', 'Alice', 'active'),
    (2, 'bob',   'x', 'Bob',   'active'),
    (3, 'gone',  'x', 'Gone',  'disabled');

-- ============ 事件投递与事实表（§19.6 / §8.3）：列名列序与 deploy/migrations/V8 一致 ============
CREATE TABLE event_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(64) NOT NULL UNIQUE,
    session_id      VARCHAR(64),
    turn_id         VARCHAR(64),
    payload         VARCHAR(8000) NOT NULL,
    attempts        INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT now(),
    last_error      VARCHAR(500),
    delivered_at    TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE event_dead_letter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    payload     VARCHAR(8000) NOT NULL,
    error       VARCHAR(500),
    retry_count INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_turn (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         VARCHAR(64) NOT NULL UNIQUE,
    session_id       VARCHAR(64) NOT NULL,
    turn_id          VARCHAR(64) NOT NULL,
    trace_id         VARCHAR(64) NOT NULL,
    user_input       VARCHAR(4000),
    final_answer     VARCHAR(4000),
    figures_json     VARCHAR(4000),
    expressions_json VARCHAR(4000),
    ledger_json      VARCHAR(4000),
    verify_result    VARCHAR(4000),
    latency_ms       BIGINT,
    created_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE agent_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    session_id  VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    trace_id    VARCHAR(64) NOT NULL,
    seq         BIGINT NOT NULL,
    type        VARCHAR(16) NOT NULL,
    content     VARCHAR(4000),
    tool_name   VARCHAR(128),
    tool_args   VARCHAR(4000),
    tool_result VARCHAR(4000),
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE tool_call (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    trace_id    VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    tool_name   VARCHAR(128) NOT NULL,
    args        VARCHAR(4000),
    result_size BIGINT,
    status      VARCHAR(16),
    error       VARCHAR(500),
    latency_ms  BIGINT,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- V16 等价物：会话状态（§19.5 / 框架 AgentStateStore 契约，agentscope-extensions-jdbc）。
-- 与 deploy/migrations/V16__agent_state_framework_store.sql 列名列序一致；
-- H2 没有 TEXT，state_data 用 CLOB（框架的 H2Dialect 也是这么建的）。
-- session_id 装的是槽位号 `<userId>:<sessionId>`，不是单纯的会话号。
CREATE TABLE agentscope_sessions (
    session_id  VARCHAR(255) NOT NULL,
    state_key   VARCHAR(255) NOT NULL,
    item_index  INT          NOT NULL DEFAULT 0,
    state_data  CLOB         NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, state_key, item_index)
);

-- V7 等价物：技能版本表里 agent 侧要读的那部分（H-06a / DR-41）。
-- 口径与 deploy/migrations/V7__skill_package_management.sql 列名列序一致；
-- agent 侧对这张表**只读**：查「这个技能现在算数的版本」（最新一条 status=published）拿 storage_key，
-- 再拿这个 key 去对象存储取包。管理端才是这张表的写者。
CREATE TABLE sys_skill_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code      VARCHAR(64)  NOT NULL,
    version         VARCHAR(32)  NOT NULL,
    content_sha256  CHAR(64)     NOT NULL UNIQUE,
    storage_key     VARCHAR(255) NOT NULL,
    manifest        VARCHAR(4000) NOT NULL,
    manifest_sha256 CHAR(64)     NOT NULL,
    kind            VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'uploaded',
    submitted_by    VARCHAR(64)  NOT NULL,
    published_by    VARCHAR(64),
    published_at    TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL,
    UNIQUE (skill_code, version)
);

-- V17 等价物：工作区共享表（H-04，框架 BaseStore 契约；agent-service.workspace-store=jdbc 时用）。
-- 与 deploy/migrations/V17__workspace_store.sql 列名列序一致；H2 没有 TEXT，value_json 用 CLOB（框架的 H2Dialect 也这么建）。
-- 装配时 PlatformWorkspaceStore 会确认这张表在，缺表直接启动失败。
CREATE TABLE agentscope_store (
    namespace_path VARCHAR(2048) NOT NULL,
    item_key       VARCHAR(255)  NOT NULL,
    value_json     CLOB          NOT NULL,
    version        BIGINT        NOT NULL,
    updated_at     BIGINT        NOT NULL,
    PRIMARY KEY (namespace_path, item_key)
);
