-- agent-service 测试 schema：只保留它真正读的一列（§19.4 入口查账号状态）。
CREATE TABLE sys_user (
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'active'
);

INSERT INTO sys_user (id, username, password_hash, display_name, status) VALUES
    (1, 'alice', 'x', 'Alice', 'active'),
    (2, 'bob',   'x', 'Bob',   'active'),
    (3, 'gone',  'x', 'Gone',  'disabled');

-- ============ 事件投递与事实表（§19.6 / §8.3）：列名列序与 deploy/migrations/V8 一致 ============
CREATE TABLE event_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(64) NOT NULL UNIQUE,
    session_id      VARCHAR(64),
    turn_id         VARCHAR(64),
    payload         VARCHAR(8000) NOT NULL,
    attempts        INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT now(),
    last_error      VARCHAR(500),
    delivered_at    TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE event_dead_letter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    payload     VARCHAR(8000) NOT NULL,
    error       VARCHAR(500),
    retry_count INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_turn (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         VARCHAR(64) NOT NULL UNIQUE,
    session_id       VARCHAR(64) NOT NULL,
    turn_id          VARCHAR(64) NOT NULL,
    trace_id         VARCHAR(64) NOT NULL,
    user_input       VARCHAR(4000),
    final_answer     VARCHAR(4000),
    figures_json     VARCHAR(4000),
    expressions_json VARCHAR(4000),
    ledger_json      VARCHAR(4000),
    verify_result    VARCHAR(4000),
    latency_ms       BIGINT,
    created_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE agent_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    session_id  VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    trace_id    VARCHAR(64) NOT NULL,
    seq         BIGINT NOT NULL,
    type        VARCHAR(16) NOT NULL,
    content     VARCHAR(4000),
    tool_name   VARCHAR(128),
    tool_args   VARCHAR(4000),
    tool_result VARCHAR(4000),
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE tool_call (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    trace_id    VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    tool_name   VARCHAR(128) NOT NULL,
    args        VARCHAR(4000),
    result_size BIGINT,
    status      VARCHAR(16),
    error       VARCHAR(500),
    latency_ms  BIGINT,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- V9 等价物：运行时状态落点（§19.5）。H2 侧 payload 用纯文本列（PG 是 jsonb），列名列序一致。
CREATE TABLE agent_state (
    user_id             VARCHAR(64)  NOT NULL,
    session_id          VARCHAR(64)  NOT NULL,
    state_key           VARCHAR(128) NOT NULL,
    runtime_id          VARCHAR(64)  NOT NULL,
    runtime_version     VARCHAR(64)  NOT NULL,
    snapshot_created_at BIGINT       NOT NULL,
    payload             VARCHAR(4000),
    updated_at          TIMESTAMP    NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, session_id, state_key)
);