-- 测试用最小 schema：列名与 deploy/migrations/V1__init_permission_session_audit.sql 对齐，
-- 但 JSONB 用 VARCHAR（PG 侧 jsonb 经 getString 读出来也是同一份 JSON 文本）。

CREATE TABLE sys_user (
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL DEFAULT '',
    display_name  VARCHAR(64)  NOT NULL DEFAULT '',
    status        VARCHAR(16) NOT NULL DEFAULT 'active'
);

CREATE TABLE sys_role (
    id        BIGINT PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_skill (
    id         BIGINT PRIMARY KEY,
    skill_code VARCHAR(64) NOT NULL UNIQUE,
    owner_type VARCHAR(16) NOT NULL DEFAULT 'platform',
    owner_id   BIGINT
);

CREATE TABLE sys_api (
    id               BIGINT PRIMARY KEY,
    name             VARCHAR(128) NOT NULL,
    service          VARCHAR(64) NOT NULL,
    http_method      VARCHAR(8) NOT NULL,
    http_path        VARCHAR(255) NOT NULL,
    kind             VARCHAR(8) NOT NULL DEFAULT 'read',
    resource         VARCHAR(128),
    param_schema     VARCHAR(4000),
    scenario         VARCHAR(2000),
    result_schema    VARCHAR(4000),
    enabled          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE role_skill (
    role_id  BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    can_view BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE skill_api (
    skill_id BIGINT NOT NULL,
    api_id   BIGINT NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (skill_id, api_id)
);

CREATE TABLE role_api (
    role_id BIGINT NOT NULL,
    api_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, api_id)
);

CREATE TABLE permission_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id       VARCHAR(64) NOT NULL,
    user_id        VARCHAR(64),
    role_ids       VARCHAR(4000),
    tool_name      VARCHAR(128),
    decision       VARCHAR(16) NOT NULL,
    reason         VARCHAR(255),
    scope_snapshot VARCHAR(4000),
    created_at     TIMESTAMP
);

CREATE TABLE pending_confirm (
    confirm_id  VARCHAR(64) PRIMARY KEY,
    session_id  VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64),
    user_id     VARCHAR(64) NOT NULL,
    action      VARCHAR(128),
    summary     VARCHAR(1000),
    status      VARCHAR(16) NOT NULL DEFAULT 'pending',
    expires_at  TIMESTAMP,
    created_at  TIMESTAMP DEFAULT now(),
    resolved_at TIMESTAMP
);

CREATE TABLE config_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who        VARCHAR(64) NOT NULL,
    target     VARCHAR(64) NOT NULL,
    field      VARCHAR(128) NOT NULL,
    before     VARCHAR(4000),
    after      VARCHAR(4000),
    request_id VARCHAR(64),
    created_at TIMESTAMP
);

CREATE TABLE data_access_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     VARCHAR(64) NOT NULL,
    trace_id       VARCHAR(64),
    caller_key_id  VARCHAR(64),
    user_id        VARCHAR(64) NOT NULL,
    service        VARCHAR(64),
    http_method    VARCHAR(8),
    http_path      VARCHAR(255),
    skill_code     VARCHAR(64),
    scope_snapshot VARCHAR(4000),
    outcome        VARCHAR(24) NOT NULL,
    reason         VARCHAR(255),
    row_count      INT,
    truncated      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP
);

CREATE TABLE refresh_token (
    token_hash VARCHAR(64) PRIMARY KEY,
    user_id    VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT now()
);

-- 「谁在何时查了审计」（§20.4）：由可写连接写入，审计内容本身走只读连接。
CREATE TABLE audit_read_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who        VARCHAR(64) NOT NULL,
    action     VARCHAR(64) NOT NULL,
    params     VARCHAR(4000),
    outcome    VARCHAR(16) NOT NULL,
    row_count  INT,
    reason     VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

-- ============ 事件投递与事实表（§19.6 / §8.3）============
-- PG 侧是 jsonb + ON CONFLICT，H2 侧用 VARCHAR + MERGE：列名列序与 deploy/migrations/V8 一致。
CREATE TABLE event_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(64) NOT NULL UNIQUE,
    session_id      VARCHAR(64),
    turn_id         VARCHAR(64),
    payload         VARCHAR(8000) NOT NULL,
    attempts        INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT now(),
    last_error      VARCHAR(500),
    delivered_at    TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE event_dead_letter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    payload     VARCHAR(8000) NOT NULL,
    error       VARCHAR(500),
    retry_count INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_turn (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         VARCHAR(64) NOT NULL UNIQUE,
    session_id       VARCHAR(64) NOT NULL,
    turn_id          VARCHAR(64) NOT NULL,
    trace_id         VARCHAR(64) NOT NULL,
    user_input       VARCHAR(4000),
    final_answer     VARCHAR(4000),
    figures_json     VARCHAR(4000),
    expressions_json VARCHAR(4000),
    ledger_json      VARCHAR(4000),
    verify_result    VARCHAR(4000),
    latency_ms       BIGINT,
    created_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE agent_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    session_id  VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    trace_id    VARCHAR(64) NOT NULL,
    seq         BIGINT NOT NULL,
    type        VARCHAR(16) NOT NULL,
    content     VARCHAR(4000),
    tool_name   VARCHAR(128),
    tool_args   VARCHAR(4000),
    tool_result VARCHAR(4000),
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE tool_call (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL UNIQUE,
    trace_id    VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    tool_name   VARCHAR(128) NOT NULL,
    args        VARCHAR(4000),
    result_size BIGINT,
    status      VARCHAR(16),
    error       VARCHAR(500),
    latency_ms  BIGINT,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

