package com.djzy.assistant.agentweb.skill;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.djzy.assistant.common.skill.PackageContent;
import com.djzy.assistant.common.storage.ObjectStorage;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * 技能包来源（H-06a / DR-41）：**认版本读管理端的表，取字节读对象存储**。
 *
 * <p>这里要钉住的是一条容易被改错的口径：「这个技能现在算数的是哪一版」。
 * 答案**不是**「最新那一封」，而是**「最新那一封已发布的」**——管理端上传和发布是两步，
 * 上传完还没发布的那一版根本不该被下发。搞错这一条，管理员「先传上去看看」的包就直接上线了。
 *
 * <p>表在用例里就地建（和生产同一份迁移脚本同口径的最小列集：主键 / 技能编码 / 版本 / 内容哈希 /
 * 存储键 / 状态），读出来的是真 SQL，不是假的仓储；对象存储用内存实现替身，只为了不依赖 MinIO。
 */
class RegistrySkillPackageSourceTest {

    private static final String CODE = "doctor_income";

    private JdbcDataSource dataSource;
    private FakeStorage storage;
    private RegistrySkillPackageSource source;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:skill-registry-" + System.nanoTime()
                + ";DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE sys_skill_version ("
                    + "  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  skill_code      VARCHAR(64)  NOT NULL,"
                    + "  version         VARCHAR(32)  NOT NULL,"
                    + "  content_sha256  CHAR(64)     NOT NULL UNIQUE,"
                    + "  storage_key     VARCHAR(255) NOT NULL,"
                    + "  status          VARCHAR(16)  NOT NULL DEFAULT 'uploaded'"
                    + ")");
        }
        storage = new FakeStorage();
        source = new RegistrySkillPackageSource(dataSource, storage);
    }

    @Test
    void 取的是最新一条已发布() throws Exception {
        version("1.0.0", "published", "k1");
        version("2.0.0", "published", "k2");

        SkillPackageSource.Published found = source.published(List.of(CODE)).get(CODE);

        assertEquals("2.0.0", found.version());
        assertEquals("k2", found.storageKey());
    }

    @Test
    void 最新一封还没发布时_回落到上一次发布的版本() throws Exception {
        version("1.0.0", "published", "k1");
        version("2.0.0", "checked", "k2");

        assertEquals("1.0.0", source.published(List.of(CODE)).get(CODE).version(),
                "上传了没发布的包不该顶掉线上那一版");
    }

    @Test
    void 从没发布过的技能_不出现在结果里() throws Exception {
        version("1.0.0", "uploaded", "k1");

        assertTrue(source.published(List.of(CODE)).isEmpty(), "没有已发布的版本 = 这次不下发，不是错误");
    }

    @Test
    void 只返回问到的技能() throws Exception {
        version("1.0.0", "published", "k1");
        versionWithCode("doctor_performance", "1.0.0", "published", "k9");

        assertEquals(Set.of(CODE), source.published(List.of(CODE)).keySet());
    }

    @Test
    void 空清单_连库都不查() {
        assertTrue(source.published(List.of()).isEmpty());
        assertTrue(source.published(null).isEmpty());
    }

    @Test
    void load_去对象存储取包并解开() {
        storage.put("k1", zip(Map.of("manifest.json", manifestJson("1.0.0"), "scripts/run.py", "print(1)")));

        Optional<PackageContent> content = source.load(new SkillPackageSource.Published(CODE, "1.0.0", "sha", "k1"));

        assertTrue(content.isPresent());
        assertEquals("收入查询", content.get().manifest().name());
        assertTrue(content.get().has("scripts/run.py"), "包内文件要解出来——下发时要原样写进工作区");
    }

    @Test
    void 存储里没有这个键_load给空而不报错() {
        assertTrue(source.load(new SkillPackageSource.Published(CODE, "1.0.0", "sha", "missing")).isEmpty());
    }

    @Test
    void 存储里那份坏了_load给空而不报错() {
        storage.put("k1", "不是 zip".getBytes(StandardCharsets.UTF_8));

        assertTrue(source.load(new SkillPackageSource.Published(CODE, "1.0.0", "sha", "k1")).isEmpty());
    }

    // ---------- 脚手架 ----------

    private void version(String version, String status, String storageKey) throws Exception {
        versionWithCode(CODE, version, status, storageKey);
    }

    private void versionWithCode(String code, String version, String status, String storageKey) throws Exception {
        try (Connection conn = dataSource.getConnection();
                PreparedStatement ps = conn.prepareStatement("INSERT INTO sys_skill_version"
                        + " (skill_code, version, content_sha256, storage_key, status) VALUES (?, ?, ?, ?, ?)")) {
            ps.setString(1, code);
            ps.setString(2, version);
            ps.setString(3, sha64(code + "-" + version + "-" + status));
            ps.setString(4, storageKey);
            ps.setString(5, status);
            ps.executeUpdate();
        }
    }

    /** 内容哈希列是 CHAR(64) 且唯一：用例里给每行造一个互不相同的 64 字符值就够。 */
    private static String sha64(String seed) {
        StringBuilder padded = new StringBuilder();
        while (padded.length() < 64) {
            padded.append(seed).append("-");
        }
        return padded.substring(0, 64);
    }

    private static String manifestJson(String version) {
        return "{\"id\":\"" + CODE + "\",\"name\":\"收入查询\",\"version\":\"" + version + "\",\"kind\":\"agentic\"}";
    }

    private static byte[] zip(Map<String, String> files) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (ZipOutputStream zip = new ZipOutputStream(out)) {
            for (Map.Entry<String, String> file : files.entrySet()) {
                zip.putNextEntry(new ZipEntry(file.getKey()));
                zip.write(file.getValue().getBytes(StandardCharsets.UTF_8));
                zip.closeEntry();
            }
        } catch (Exception e) {
            throw new AssertionError("造包失败", e);
        }
        return out.toByteArray();
    }

    /** 对象存储的内存替身：只为了不依赖 MinIO。 */
    private static final class FakeStorage implements ObjectStorage {

        private final Map<String, byte[]> objects = new LinkedHashMap<>();

        void put(String key, byte[] content) {
            objects.put(key, content);
        }

        @Override
        public boolean putIfAbsent(String key, byte[] content) {
            return objects.putIfAbsent(key, content) == null;
        }

        @Override
        public Optional<byte[]> get(String key) {
            return Optional.ofNullable(objects.get(key));
        }

        @Override
        public boolean exists(String key) {
            return objects.containsKey(key);
        }

        @Override
        public List<String> list(String prefix) {
            return objects.keySet().stream().filter(key -> key.startsWith(prefix)).sorted().toList();
        }

        @Override
        public void delete(String key) {
            objects.remove(key);
        }
    }
}
