-- 管理后台测试 schema：账号 / 角色 / 接口注册 / 授权 / 配置审计 / 刷新令牌。
-- 与 deploy/migrations/V1–V4 的列名对齐（jsonb → VARCHAR，PG 侧读到的是同一份 JSON 文本）。

CREATE TABLE sys_user (
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'active'
);

CREATE TABLE sys_role (
    id        BIGINT PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_skill (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code   VARCHAR(64)  NOT NULL UNIQUE,
    name         VARCHAR(128) NOT NULL DEFAULT '',
    description  VARCHAR(4000),
    owner_type   VARCHAR(16)  NOT NULL DEFAULT 'platform',
    owner_id     BIGINT,
    read_only    BOOLEAN      NOT NULL DEFAULT TRUE,
    param_schema VARCHAR(4000),
    status       VARCHAR(16)  NOT NULL DEFAULT 'draft',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_skill (
    role_id  BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    can_view BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE skill_api (
    skill_id    BIGINT      NOT NULL,
    api_id      BIGINT      NOT NULL,
    approved    BOOLEAN     NOT NULL DEFAULT FALSE,
    approved_by VARCHAR(64),
    approved_at TIMESTAMP,
    PRIMARY KEY (skill_id, api_id)
);

CREATE TABLE sys_api (
    -- 起始值避开下面演示种子的显式 id（1 / 2），等价于 PG 侧的 BIGSERIAL
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,
    name     VARCHAR(128) NOT NULL,
    service  VARCHAR(64)  NOT NULL,
    http_method VARCHAR(8)   NOT NULL,
    http_path   VARCHAR(255) NOT NULL,
    kind        VARCHAR(8)   NOT NULL DEFAULT 'read',
    resource VARCHAR(128),
    param_schema     VARCHAR(4000),
    scenario         VARCHAR(2000),
    result_schema    VARCHAR(4000),
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP
);

-- 口径字典（§6.1 / V5 规格字段）。
CREATE TABLE metric_dictionary (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_key VARCHAR(64)  NOT NULL UNIQUE,
    domain     VARCHAR(64),
    name       VARCHAR(128) NOT NULL,
    aliases    VARCHAR(4000),
    definition VARCHAR(4000),
    formula    VARCHAR(4000),
    time_basis VARCHAR(32),
    unit       VARCHAR(32),
    scale      NUMERIC(18, 6),
    rounding   INT NOT NULL DEFAULT 1,
    derived_of VARCHAR(4000),
    timezone   VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    basis      VARCHAR(4000),
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP
);

CREATE TABLE unit_convert (
    from_unit VARCHAR(32)    NOT NULL,
    to_unit   VARCHAR(32)    NOT NULL,
    factor    NUMERIC(18, 6) NOT NULL,
    PRIMARY KEY (from_unit, to_unit)
);

-- 审计四件事：判定 / 数据访问 / 审计读（配置变更见 config_audit）。
CREATE TABLE permission_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id       VARCHAR(64) NOT NULL,
    user_id        VARCHAR(64),
    role_ids       VARCHAR(4000),
    tool_name      VARCHAR(128),
    decision       VARCHAR(16) NOT NULL,
    reason         VARCHAR(255),
    scope_snapshot VARCHAR(4000),
    created_at     TIMESTAMP NOT NULL
);

CREATE TABLE data_access_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     VARCHAR(64) NOT NULL,
    trace_id       VARCHAR(64),
    caller_key_id  VARCHAR(64),
    user_id        VARCHAR(64) NOT NULL,
    service        VARCHAR(64),
    http_method    VARCHAR(8),
    http_path      VARCHAR(255),
    skill_code     VARCHAR(64),
    scope_snapshot VARCHAR(4000),
    outcome        VARCHAR(24) NOT NULL,
    reason         VARCHAR(255),
    row_count      INT,
    truncated      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP NOT NULL
);

CREATE TABLE audit_read_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who        VARCHAR(64) NOT NULL,
    action     VARCHAR(64) NOT NULL,
    params     VARCHAR(4000),
    outcome    VARCHAR(16) NOT NULL,
    row_count  INT,
    reason     VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

-- 编排侧事实表（回放用，§8.3）。
CREATE TABLE conversation_turn (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         VARCHAR(64) NOT NULL,
    session_id       VARCHAR(64) NOT NULL,
    turn_id          VARCHAR(64) NOT NULL,
    trace_id         VARCHAR(64) NOT NULL,
    user_input       VARCHAR(4000),
    context_snapshot VARCHAR(4000),
    final_answer     VARCHAR(4000),
    figures_json     VARCHAR(4000),
    expressions_json VARCHAR(4000),
    ledger_json      VARCHAR(4000),
    verify_result    VARCHAR(4000),
    latency_ms       BIGINT,
    created_at       TIMESTAMP NOT NULL
);

CREATE TABLE agent_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    session_id  VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64) NOT NULL,
    trace_id    VARCHAR(64) NOT NULL,
    seq         BIGINT NOT NULL,
    type        VARCHAR(16) NOT NULL,
    content     VARCHAR(4000),
    tool_name   VARCHAR(128),
    tool_args   VARCHAR(4000),
    tool_result VARCHAR(4000),
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE llm_call (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         VARCHAR(64) NOT NULL,
    trace_id         VARCHAR(64) NOT NULL,
    turn_id          VARCHAR(64),
    model            VARCHAR(64),
    prompt_hash      VARCHAR(64),
    prompt_preview   VARCHAR(4000),
    response_preview VARCHAR(4000),
    tokens_in        INT,
    tokens_out       INT,
    cost             NUMERIC(18, 6),
    latency_ms       BIGINT,
    status           VARCHAR(16),
    created_at       TIMESTAMP NOT NULL
);

CREATE TABLE tool_call (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    trace_id    VARCHAR(64) NOT NULL,
    turn_id     VARCHAR(64),
    tool_name   VARCHAR(128) NOT NULL,
    args        VARCHAR(4000),
    result_size BIGINT,
    status      VARCHAR(16),
    error       VARCHAR(4000),
    latency_ms  BIGINT,
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE role_api (
    role_id BIGINT NOT NULL,
    api_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, api_id)
);

CREATE TABLE config_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who        VARCHAR(64) NOT NULL,
    target     VARCHAR(64) NOT NULL,
    field      VARCHAR(128) NOT NULL,
    before     VARCHAR(4000),
    after      VARCHAR(4000),
    request_id VARCHAR(64),
    created_at TIMESTAMP
);

CREATE TABLE refresh_token (
    token_hash VARCHAR(64) PRIMARY KEY,
    user_id    VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT now()
);

-- 演示账号：admin（admin 角色）、alice（boss 角色，用于验证非管理员被拒）。
INSERT INTO sys_role (id, role_code) VALUES (1, 'admin'), (2, 'boss');

-- 口令哈希由 PasswordHasher 生成（固定盐仅用于演示种子；真实部署由账号管理写入）。
INSERT INTO sys_user (id, username, password_hash, display_name, status) VALUES
    (1, 'admin', 'pbkdf2$210000$ZGVtby1zZWVkLXNhbHQtMQ$K77tBEhbW8OdRspFMJPm+qO/4hlwXPLP2GggxeG4TTI', '系统管理员', 'active'),
    (2, 'alice', 'pbkdf2$210000$ZGVtby1zZWVkLXNhbHQtMg$BwUNs0RSoSAld8rgWszI5RTM/NKRr17CjxngL0rYovM', '张医生', 'active'),
    (3, 'gone',  'pbkdf2$210000$ZGVtby1zZWVkLXNhbHQtMg$BwUNs0RSoSAld8rgWszI5RTM/NKRr17CjxngL0rYovM', '已停用', 'disabled');

INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1), (2, 2), (3, 2);

-- 演示种子与 deploy/migrations/V11 + V12 对齐：参数契约与返回字段契约都要有，
-- 否则 M3 的「导出列必须落在绑定接口的返回字段契约内」会被误判成不通过。
INSERT INTO sys_api (id, name, service, http_method, http_path, kind, enabled, param_schema, result_schema) VALUES
    (1, '医生绩效', 'interface-doctor', 'POST', '/doctor/performance', 'read', TRUE,
     '{"type":"object","required":["month","metric_key"],"properties":{"month":{"type":"string"},"metric_key":{"type":"string"},"doctor_id":{"type":"string"},"dept_code":{"type":"string"}}}',
     '{"doctor_id":{"type":"string"},"doctor_name":{"type":"string"},"dept_code":{"type":"string"},"stat_month":{"type":"string"},"metric_key":{"type":"string"},"metric_value":{"type":"number"}}'),
    (2, '医生列表', 'interface-doctor', 'POST', '/doctor/list', 'read', TRUE,
     '{"type":"object","properties":{"dept_code":{"type":"string"}}}',
     '{"doctor_id":{"type":"string"},"doctor_name":{"type":"string"},"dept_code":{"type":"string"}}');
-- M3 技能包管理（V7）：内容寻址的版本表 + 自动检查明细 + 人工评审记录。
CREATE TABLE sys_skill_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code      VARCHAR(64)  NOT NULL,
    version         VARCHAR(32)  NOT NULL,
    content_sha256  CHAR(64)     NOT NULL UNIQUE,
    storage_key     VARCHAR(255) NOT NULL,
    manifest        VARCHAR(4000) NOT NULL,
    manifest_sha256 CHAR(64)     NOT NULL,
    kind            VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'uploaded',
    submitted_by    VARCHAR(64)  NOT NULL,
    published_by    VARCHAR(64),
    published_at    TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL,
    UNIQUE (skill_code, version)
);

CREATE TABLE skill_check (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_version_id BIGINT      NOT NULL,
    check_code       VARCHAR(64) NOT NULL,
    severity         VARCHAR(16) NOT NULL,
    passed           BOOLEAN     NOT NULL,
    detail           VARCHAR(4000),
    created_at       TIMESTAMP   NOT NULL
);

CREATE TABLE skill_review (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_version_id BIGINT      NOT NULL,
    decision         VARCHAR(16) NOT NULL,
    reviewer         VARCHAR(64) NOT NULL,
    reason           VARCHAR(4000),
    exported_columns VARCHAR(4000),
    created_at       TIMESTAMP   NOT NULL
);

-- V10：LLM 供应商配置（ADR-14 / §20.1.6）。
-- H2 没有部分唯一索引，「同一时刻至多一个 enabled」在测试里由服务层的
-- disableOthers + 用例断言保证；PG 侧另有 ux_sys_llm_provider_enabled 兜底。
-- created_at / updated_at 给 CURRENT_TIMESTAMP 默认值：生产 SQL 靠 now() 默认值，
-- 测试库必须同样能「不给时间戳也插得进去」，否则测的就不是同一套 SQL 语义。
CREATE TABLE sys_llm_provider (
    provider_id    VARCHAR(64)   PRIMARY KEY,
    adapter        VARCHAR(32)   NOT NULL,
    base_url       VARCHAR(255)  NOT NULL,
    model          VARCHAR(128)  NOT NULL,
    api_key_cipher VARCHAR(1000) NOT NULL,
    key_hint       VARCHAR(64)   NOT NULL,
    enabled        BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
