-- 接口服务测试 schema：只建业务表与 I6 审计表。
-- 故意**没有** sys_user / sys_role / role_api 等权限表——接口服务不查权限库、不重算范围（§20.1.6-6）；
-- 若有人在这里塞进权限查询，这个 schema 会立刻让它跑不起来（这正是我们要的护栏）。

CREATE TABLE doctor_metric (
    doctor_id    VARCHAR(64) NOT NULL,
    doctor_name  VARCHAR(64),
    dept_code    VARCHAR(64) NOT NULL,
    stat_month   VARCHAR(7)  NOT NULL,
    metric_key   VARCHAR(64) NOT NULL,
    metric_value NUMERIC(18, 2)
);

INSERT INTO doctor_metric (doctor_id, doctor_name, dept_code, stat_month, metric_key, metric_value) VALUES
    ('1', '张医生', '心内科', '2026-08', 'outpatient_visits', 120),
    ('2', '李医生', '心内科', '2026-08', 'outpatient_visits',  90),
    ('7', '王医生', '呼吸科', '2026-08', 'outpatient_visits',  75),
    ('8', '赵医生', '呼吸科', '2026-08', 'drug_ratio',        0.31),
    ('9', '钱医生', '财务科', '2026-08', 'outpatient_visits',  10);

CREATE TABLE metric_dictionary (
    metric_key VARCHAR(64) PRIMARY KEY,
    name       VARCHAR(128) NOT NULL,
    unit       VARCHAR(32),
    rounding   INT NOT NULL DEFAULT 1,
    basis      VARCHAR(255),
    enabled    BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO metric_dictionary (metric_key, name, unit, rounding, basis, enabled) VALUES
    ('outpatient_visits', '门诊人次', '人次', 0, '按挂号口径统计', TRUE),
    ('drug_ratio',        '药占比',   '%',   2, '药品收入 / 医疗收入', TRUE);

CREATE TABLE data_access_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     VARCHAR(64) NOT NULL,
    trace_id       VARCHAR(64),
    caller_key_id  VARCHAR(64),
    user_id        VARCHAR(64) NOT NULL,
    service        VARCHAR(64),
    http_method    VARCHAR(8),
    http_path      VARCHAR(255),
    skill_code     VARCHAR(64),
    scope_snapshot VARCHAR(4000),
    outcome        VARCHAR(24) NOT NULL,
    reason         VARCHAR(255),
    row_count      INT,
    truncated      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP
);

-- 接口注册表：启动自检（RegisteredRouteCatalog）要与它对账——**故意保留这张表**，
-- 因为"注册表说有哪些接口"与"代码里实现了哪些接口"必须一致，测试里也要跑同一条对账逻辑。
-- param_schema 的 properties 必须与各接口的入参 record 字段逐一对上，否则接口服务拒绝启动。
CREATE TABLE sys_api (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    service      VARCHAR(64)  NOT NULL,
    http_method  VARCHAR(8)   NOT NULL,
    http_path    VARCHAR(255) NOT NULL,
    kind         VARCHAR(8)   NOT NULL DEFAULT 'read',
    resource     VARCHAR(128),
    param_schema VARCHAR(4000),
    scenario     VARCHAR(2000),
    result_schema VARCHAR(4000),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO sys_api (name, service, http_method, http_path, kind, resource, param_schema) VALUES
    ('医生绩效', 'interface-doctor', 'POST', '/doctor/performance', 'read', 'doctor',
     '{"type":"object","required":["month","metric_key"],"properties":{"month":{"type":"string"},"metric_key":{"type":"string"},"doctor_id":{"type":"string"},"dept_code":{"type":"string"}},"additionalProperties":false}'),
    ('医生名单', 'interface-doctor', 'POST', '/doctor/list', 'read', 'doctor',
     '{"type":"object","properties":{"dept_code":{"type":"string"}},"additionalProperties":false}');
-- 工件登记表（§18.4.5 W3）：上传到对象存储的导出件在这里留一条可查记录。
-- 它**不是权限表**（接口服务依然不查权限库），所以放在这里不违反本 schema 的护栏。
CREATE TABLE artifact (
    artifact_id VARCHAR(64) PRIMARY KEY,
    session_id  VARCHAR(64),
    turn_id     VARCHAR(64),
    name        VARCHAR(255),
    size_bytes  BIGINT,
    locator     TEXT NOT NULL,
    expires_at  TIMESTAMP,
    created_at  TIMESTAMP
);

-- 导出上传（写接口）：kind=write 才会触发写操作确认门（§18.4.5 W1）。
-- param_schema.properties 必须与 DoctorExportUploadApi.Args 的字段逐一对上，否则接口服务拒绝启动。
INSERT INTO sys_api (name, service, http_method, http_path, kind, resource, param_schema, result_schema) VALUES
    ('导出文件上传', 'interface-doctor', 'POST', '/doctor/export/upload', 'write', 'oss',
     '{"type":"object","required":["file_name","content_base64"],"properties":{"file_name":{"type":"string"},"content_base64":{"type":"string"},"sandbox_path":{"type":"string"},"content_type":{"type":"string"},"session_id":{"type":"string"},"artifact_name":{"type":"string"}},"additionalProperties":false}',
     '{"type":"object","properties":{"artifact_id":{"type":"string"},"file_name":{"type":"string"},"size_bytes":{"type":"integer"},"content_sha256":{"type":"string"},"storage_key":{"type":"string"},"download_url":{"type":"string"},"download_url_expires_at":{"type":"string"},"object_expires_at":{"type":"string"}}}');